name: curriculum
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.0.8
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/perfil.jpeg
    - assets/munhoz.jpeg
    - assets/unifei.png
    - assets/aiesec.jpg
    - assets/redblue.jpeg
    - assets/wattio.jpeg
    - assets/autoponia.jpeg
    - assets/volun.jpg
    - assets/bvrbunny.jpg
    - assets/food.jpeg
    - assets/deeplearning.png
    - assets/linkedin.png
    - assets/git.png
  fonts:
    - family: Browallia
      fonts:
        - asset: assets/browallia-new.ttf
